name: iOS App Release Build

on:
  push:
    tags:
      - 'ios/v[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  build:
    runs-on: xcode-27
    steps:
      - name: Setup repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Setup
        uses: ./tooling/github/setup

      - name: Setup Expo
        uses: expo/expo-github-action@c7b66a9c327a43a8fa7c0158e7f30d6040d2481e # v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build iOS app
        working-directory: apps/mobile
        run: eas build --platform ios --local --non-interactive --output ${{ github.workspace }}/app-release.ipa
        env:
          EAS_SKIP_AUTO_FINGERPRINT: "1"
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Upload IPA artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: karakeep-ios
          path: ${{ github.workspace }}/app-release.ipa
